-- Generated for IdentityExpress6 using the IdentityDbContext in https://github.com/RockSolidKnowledge/Samples.OpenIddict.AdminUI

START TRANSACTION;

CREATE TABLE "AspNetClaimTypes" (
    "Id" text NOT NULL,
    "Name" character varying(256) NOT NULL,
    "NormalizedName" character varying(256),
    "DisplayName" text,
    "Description" text,
    "Required" boolean NOT NULL,
    "Reserved" boolean NOT NULL,
    "ValueType" integer NOT NULL,
    "Rule" text,
    "RuleValidationFailureDescription" text,
    "ConcurrencyStamp" text,
    "UserEditable" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_AspNetClaimTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_AspNetClaimTypes_Name" UNIQUE ("Name")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Description" text,
    "Reserved" boolean NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "FirstName" text,
    "NormalizedFirstName" character varying(256),
    "LastName" text,
    "NormalizedLastName" character varying(256),
    "IsBlocked" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "EnumClaimTypeAllowedValues" (
    "ClaimTypeId" text NOT NULL,
    "Value" text NOT NULL,
    CONSTRAINT "PK_EnumClaimTypeAllowedValues" PRIMARY KEY ("ClaimTypeId", "Value"),
    CONSTRAINT "FK_EnumClaimTypeAllowedValues_AspNetClaimTypes_ClaimTypeId" FOREIGN KEY ("ClaimTypeId") REFERENCES "AspNetClaimTypes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" character varying(256) NOT NULL,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetClaimTypes_ClaimType" FOREIGN KEY ("ClaimType") REFERENCES "AspNetClaimTypes" ("Name") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "ClaimTypeNameIndex" ON "AspNetClaimTypes" ("NormalizedName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_ClaimType" ON "AspNetUserClaims" ("ClaimType");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "CountIndex" ON "AspNetUsers" ("IsBlocked", "IsDeleted");

CREATE INDEX "CountIndexReversed" ON "AspNetUsers" ("IsDeleted", "IsBlocked");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "FirstNameIndex" ON "AspNetUsers" ("NormalizedFirstName");

CREATE INDEX "LastNameIndex" ON "AspNetUsers" ("NormalizedLastName");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

COMMIT;

